name: estoyenello
favicon: null
layout_spectrum: 0.15192085853777826
typography_spectrum: 0.2964087584987283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.16944996127858758
  lightness: 0.24436195730231702
  saturation: 0.7537083134520799
  rhythmicContrast: 0.4204031478147954
purpose: []
